'use client';

// src/app/dashboard/e/[slug]/SummaryPanel.tsx
//
// Owner-side AI meeting summary panel. GET shows the latest stored summary;
// POST regenerates by calling OpenAI on the server.

import { useEffect, useState, useCallback } from "react";

type Summary = { text: string; model: string; generatedAt: number };

type Props = { eventId: string; initial?: Summary | null };

export default function SummaryPanel({ eventId, initial = null }: Props) {
  const [summary, setSummary] = useState<Summary | null>(initial);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    setErr(null);
    try {
      const r = await fetch(`/api/events/${eventId}/summary`, { cache: "no-store" });
      const j = await r.json();
      if (!r.ok) throw new Error(j.error || "Failed to load summary");
      setSummary(j.summary || null);
    } catch (e: any) {
      setErr(e?.message || "Failed to load");
    }
  }, [eventId]);

  useEffect(() => { if (!initial) refresh(); }, [initial, refresh]);

  const generate = async () => {
    setBusy(true);
    setErr(null);
    try {
      const r = await fetch(`/api/events/${eventId}/summary`, { method: "POST" });
      const j = await r.json();
      if (!r.ok) {
        if (j.error === "openai_not_configured") {
          throw new Error("OpenAI is not configured. Set OPENAI_API_KEY in env.");
        }
        if (j.error === "no_content") {
          throw new Error("Nothing to summarize yet (no transcript or chat).");
        }
        throw new Error(j.error || "Failed to generate summary");
      }
      setSummary(j.summary || null);
    } catch (e: any) {
      setErr(e?.message || "Failed");
    } finally {
      setBusy(false);
    }
  };

  const copy = async () => {
    if (!summary?.text) return;
    try { await navigator.clipboard.writeText(summary.text); } catch {}
  };

  return (
    <section className={"rounded-2xl border border-cyan-500/15 bg-slate-900/40 backdrop-blur p-5 space-y-3"}>
      <header className={"flex items-center justify-between"}>
        <h2 className={"text-sm uppercase tracking-widest text-slate-400"}>AI Summary</h2>
        <div className={"flex items-center gap-2"}>
          {summary && <button type={"button"} onClick={copy} className={"text-[11px] px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300"}>Copy</button>}
          <button type={"button"} onClick={generate} disabled={busy} className={"text-xs px-3 py-1.5 rounded bg-cyan-500/20 hover:bg-cyan-500/30 border border-cyan-400/40 text-cyan-200 disabled:opacity-50"}>{busy ? "Generating..." : (summary ? "Regenerate" : "Generate")}</button>
        </div>
      </header>

      {err && <div className={"text-xs text-rose-300 bg-rose-500/10 border border-rose-500/30 rounded px-3 py-2"}>{err}</div>}

      {summary ? (
        <div>
          <div className={"text-[10px] text-slate-500 mb-2"}>Generated by {summary.model} at {new Date(summary.generatedAt).toLocaleString()}</div>
          <pre className={"whitespace-pre-wrap text-xs text-slate-200 bg-slate-950/60 border border-slate-800 rounded p-3 leading-relaxed font-sans"}>{summary.text}</pre>
        </div>
      ) : !err ? (
        <div className={"text-xs text-slate-500"}>No summary yet. Click Generate after the meeting has produced a transcript or chat history.</div>
      ) : null}
    </section>
  );
}
