// src/app/api/events/[id]/transcript/export/route.ts
//
// GET — download the meeting transcript as TXT / RTF / DOCX.
//
// Query
//   format = txt | rtf | docx           (required)
//   key    = <transcript artifact key>  (optional; defaults to newest)
//
// FRS §8.4 lists RTF/DOCX/TXT/PDF. PDF is deferred to its own PR — pdf-lib
// text-layout on Vercel wants a bundled font, worth a separate lane.
//
// FRS §8.5 asks for speaker/timestamp metadata + paragraph separation by
// speaker. The current transcribe pipeline stores raw text only (segments
// are a follow-up on the transcribe side); this exporter renders whatever
// the artifact carries with a title/date header, and paragraph splits on
// blank lines so the shape is right for when segments do arrive.
//
// Authorization: transcript:read (RANK.host).

import { NextResponse, type NextRequest } from "next/server";
import { authorize } from "@/lib/authz";
import { eventStore } from "@/lib/eventStore";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Format = "txt" | "rtf" | "docx";

function isFormat(v: string): v is Format {
  return v === "txt" || v === "rtf" || v === "docx";
}

const CONTENT_TYPES: Record<Format, string> = {
  txt: "text/plain; charset=utf-8",
  rtf: "application/rtf",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
};

function safeFileSlug(event: { slug?: string; id: string }): string {
  return (event.slug || event.id).replace(/[^a-z0-9-]+/gi, "-");
}

function paragraphsFrom(text: string): string[] {
  return text
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
}

function rtfEscape(input: string): string {
  return input.replace(/\\/g, "\\\\").replace(/[{}]/g, (m) => "\\" + m);
}

function buildTxt(title: string, date: string, paragraphs: string[]): string {
  const header = [`${title}`, `Date: ${date}`, `Generated by NeoConference`, ""].join("\n");
  return header + "\n" + paragraphs.join("\n\n") + "\n";
}

function buildRtf(title: string, date: string, paragraphs: string[]): string {
  const header = String.raw`{\rtf1\ansi\ansicpg1252\deff0` +
    String.raw`{\fonttbl{\f0\fnil\fcharset0 Calibri;}}` +
    String.raw`{\*\generator NeoConference;}` +
    String.raw`\viewkind4\uc1\pard\sa200\sl276\slmult1\lang9`;
  const titleBlock = String.raw`\pard\qc\b\fs36 ` + rtfEscape(title) + String.raw`\b0\fs22\par`;
  const dateBlock = String.raw`\pard\qc\fs20 ` + rtfEscape(`Date: ${date}`) + String.raw`\par`;
  const generatedBlock = String.raw`\pard\qc\i\fs18 Generated by NeoConference\i0\par\par`;
  const body = paragraphs
    .map((p) => String.raw`\pard\ql\fs22 ` + rtfEscape(p).replace(/\n/g, String.raw`\line `) + String.raw`\par`)
    .join("");
  return header + titleBlock + dateBlock + generatedBlock + body + "}";
}

async function buildDocx(title: string, date: string, paragraphs: string[]): Promise<Buffer> {
  const doc = new Document({
    creator: "NeoConference",
    title,
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: title, bold: true })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: `Date: ${date}` })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: "Generated by NeoConference", italics: true })],
          }),
          new Paragraph({ children: [new TextRun("")] }),
          ...paragraphs.map(
            (p) =>
              new Paragraph({
                children: [new TextRun(p)],
              }),
          ),
        ],
      },
    ],
  });
  return Packer.toBuffer(doc);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const event = (await eventStore.byId(id)) ?? (await eventStore.bySlug(id));
  if (!event) return NextResponse.json({ error: "not_found" }, { status: 404 });

  const gate = await authorize(event, "transcript:read");
  if (!gate.ok) return gate.response;

  const url = new URL(req.url);
  const format = (url.searchParams.get("format") || "").toLowerCase();
  if (!isFormat(format)) {
    return NextResponse.json({ error: "invalid_format", message: "format must be txt, rtf, or docx" }, { status: 400 });
  }
  const requestedKey = url.searchParams.get("key");

  // Find the transcript artifact. The transcribe route stores text on the
  // artifact's `label` field with kind === "transcript".
  const artifacts = (event.recordings || []).filter((a) => a.kind === "transcript");
  const chosen = requestedKey
    ? artifacts.find((a) => a.key === requestedKey)
    : artifacts.sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""))[0];

  if (!chosen || !chosen.label) {
    return NextResponse.json({ error: "no_transcript" }, { status: 404 });
  }

  const title = event.name || "Meeting transcript";
  const meetingDate = event.startedAt || event.endedAt || event.createdAt || "";
  const dateLabel = meetingDate ? new Date(meetingDate).toUTCString() : "unknown";
  const paragraphs = paragraphsFrom(chosen.label);

  const fileSlug = safeFileSlug(event);
  const disposition = `attachment; filename="transcript-${fileSlug}.${format}"`;

  let body: Buffer | string;
  if (format === "txt") {
    body = buildTxt(title, dateLabel, paragraphs);
  } else if (format === "rtf") {
    body = buildRtf(title, dateLabel, paragraphs);
  } else {
    body = await buildDocx(title, dateLabel, paragraphs);
  }

  const buf = typeof body === "string" ? Buffer.from(body, "utf8") : body;

  return new NextResponse(new Uint8Array(buf), {
    status: 200,
    headers: {
      "content-type": CONTENT_TYPES[format],
      "content-disposition": disposition,
      "content-length": String(buf.byteLength),
      "cache-control": "no-store",
    },
  });
}
