// src/app/api/events/[id]/transcript/export/route.ts
//
// GET — download the meeting transcript as TXT / RTF / DOCX.
//
// Query
//   format = txt | rtf | docx           (required)
//   key    = <transcript artifact key>  (optional; defaults to newest)
//
// FRS §8.4 lists RTF/DOCX/TXT/PDF. PDF is deferred to its own PR — pdf-lib
// text-layout on Vercel wants a bundled font, worth a separate lane.
//
// FRS §8.5 asks for speaker/timestamp metadata + paragraph separation by
// speaker. The current transcribe pipeline stores raw text only (segments
// are a follow-up on the transcribe side); this exporter renders whatever
// the artifact carries with a title/date header, and paragraph splits on
// blank lines so the shape is right for when segments do arrive.
//
// Authorization: transcript:read (RANK.host).

import { NextResponse, type NextRequest } from "next/server";
import { authorize } from "@/lib/authz";
import { eventStore } from "@/lib/eventStore";
import { getTranscribeJob, type TranscriptSegment } from "@/lib/transcribe";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Format = "txt" | "rtf" | "docx";

function isFormat(v: string): v is Format {
  return v === "txt" || v === "rtf" || v === "docx";
}

const CONTENT_TYPES: Record<Format, string> = {
  txt: "text/plain; charset=utf-8",
  rtf: "application/rtf",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
};

function safeFileSlug(event: { slug?: string; id: string }): string {
  return (event.slug || event.id).replace(/[^a-z0-9-]+/gi, "-");
}

function paragraphsFrom(text: string): string[] {
  return text
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0);
}

/**
 * FRS §8.5: each rendered line carries the speaker + timestamp so the
 * transcript reads like a proper stenography record, not a wall of text.
 * Speaker labels arrive as raw provider values ("0", 1, "A") — normalize
 * to "Speaker 1", "Speaker 2" so the presentation is provider-agnostic.
 */
interface Line {
  speaker: string | null;
  timestamp: string | null;
  text: string;
}

function normalizeSpeaker(raw: string | number | undefined, index: Map<string, number>): string | null {
  if (raw === undefined || raw === null) return null;
  const key = String(raw);
  let n = index.get(key);
  if (n === undefined) {
    n = index.size + 1;
    index.set(key, n);
  }
  return `Speaker ${n}`;
}

function formatTs(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) return "00:00:00";
  const totalSec = Math.floor(ms / 1000);
  const h = Math.floor(totalSec / 3600);
  const m = Math.floor((totalSec % 3600) / 60);
  const s = totalSec % 60;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return `${pad(h)}:${pad(m)}:${pad(s)}`;
}

function linesFromSegments(segments: TranscriptSegment[]): Line[] {
  const index = new Map<string, number>();
  return segments.map((seg) => ({
    speaker: normalizeSpeaker(seg.speaker, index),
    timestamp: formatTs(seg.startMs),
    text: seg.text,
  }));
}

function linesFromText(text: string): Line[] {
  return paragraphsFrom(text).map((p) => ({ speaker: null, timestamp: null, text: p }));
}

/** Extract the job id from an artifact key. Artifacts land as "transcript:<jobId>". */
function jobIdFromArtifactKey(key: string): string | null {
  const prefix = "transcript:";
  return key.startsWith(prefix) ? key.slice(prefix.length) : null;
}

function rtfEscape(input: string): string {
  return input.replace(/\\/g, "\\\\").replace(/[{}]/g, (m) => "\\" + m);
}

function linePrefix(line: Line): string {
  if (line.speaker && line.timestamp) return `[${line.timestamp}] ${line.speaker}:`;
  if (line.timestamp) return `[${line.timestamp}]`;
  if (line.speaker) return `${line.speaker}:`;
  return "";
}

function buildTxt(title: string, date: string, lines: Line[]): string {
  const header = [`${title}`, `Date: ${date}`, `Generated by NeoConference`, ""].join("\n");
  const body = lines
    .map((line) => {
      const prefix = linePrefix(line);
      return prefix ? `${prefix}\n${line.text}` : line.text;
    })
    .join("\n\n");
  return header + "\n" + body + "\n";
}

function buildRtf(title: string, date: string, lines: Line[]): string {
  const header = String.raw`{\rtf1\ansi\ansicpg1252\deff0` +
    String.raw`{\fonttbl{\f0\fnil\fcharset0 Calibri;}}` +
    String.raw`{\*\generator NeoConference;}` +
    String.raw`\viewkind4\uc1\pard\sa200\sl276\slmult1\lang9`;
  const titleBlock = String.raw`\pard\qc\b\fs36 ` + rtfEscape(title) + String.raw`\b0\fs22\par`;
  const dateBlock = String.raw`\pard\qc\fs20 ` + rtfEscape(`Date: ${date}`) + String.raw`\par`;
  const generatedBlock = String.raw`\pard\qc\i\fs18 Generated by NeoConference\i0\par\par`;
  const body = lines
    .map((line) => {
      const prefix = linePrefix(line);
      const prefixRtf = prefix
        ? String.raw`\pard\ql\b\fs20 ` + rtfEscape(prefix) + String.raw`\b0\par`
        : "";
      const bodyRtf =
        String.raw`\pard\ql\fs22 ` +
        rtfEscape(line.text).replace(/\n/g, String.raw`\line `) +
        String.raw`\par`;
      return prefixRtf + bodyRtf;
    })
    .join("");
  return header + titleBlock + dateBlock + generatedBlock + body + "}";
}

async function buildDocx(title: string, date: string, lines: Line[]): Promise<Buffer> {
  const bodyParagraphs: Paragraph[] = [];
  for (const line of lines) {
    const prefix = linePrefix(line);
    if (prefix) {
      bodyParagraphs.push(
        new Paragraph({
          spacing: { before: 200 },
          children: [new TextRun({ text: prefix, bold: true })],
        }),
      );
    }
    bodyParagraphs.push(
      new Paragraph({
        children: [new TextRun({ text: line.text })],
      }),
    );
  }

  const doc = new Document({
    creator: "NeoConference",
    title,
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: title, bold: true })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: `Date: ${date}` })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [new TextRun({ text: "Generated by NeoConference", italics: true })],
          }),
          new Paragraph({ children: [new TextRun("")] }),
          ...bodyParagraphs,
        ],
      },
    ],
  });
  return Packer.toBuffer(doc);
}

export async function GET(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const event = (await eventStore.byId(id)) ?? (await eventStore.bySlug(id));
  if (!event) return NextResponse.json({ error: "not_found" }, { status: 404 });

  const gate = await authorize(event, "transcript:read");
  if (!gate.ok) return gate.response;

  const url = new URL(req.url);
  const format = (url.searchParams.get("format") || "").toLowerCase();
  if (!isFormat(format)) {
    return NextResponse.json({ error: "invalid_format", message: "format must be txt, rtf, or docx" }, { status: 400 });
  }
  const requestedKey = url.searchParams.get("key");

  // Find the transcript artifact. The transcribe route stores text on the
  // artifact's `label` field with kind === "transcript".
  const artifacts = (event.recordings || []).filter((a) => a.kind === "transcript");
  const chosen = requestedKey
    ? artifacts.find((a) => a.key === requestedKey)
    : artifacts.sort((a, b) => (b.createdAt || "").localeCompare(a.createdAt || ""))[0];

  if (!chosen || !chosen.label) {
    return NextResponse.json({ error: "no_transcript" }, { status: 404 });
  }

  const title = event.name || "Meeting transcript";
  const meetingDate = event.startedAt || event.endedAt || event.createdAt || "";
  const dateLabel = meetingDate ? new Date(meetingDate).toUTCString() : "unknown";

  // Prefer the diarized segments stored on the TranscribeJob (FRS §8.5).
  // Fall back to blank-line-split paragraphs on the raw text if the job is
  // gone or the provider didn't return utterances.
  let lines: Line[] = [];
  const jobId = jobIdFromArtifactKey(chosen.key);
  if (jobId) {
    const job = await getTranscribeJob(jobId).catch(() => null);
    if (job?.segments && job.segments.length > 0) {
      lines = linesFromSegments(job.segments);
    }
  }
  if (lines.length === 0) {
    lines = linesFromText(chosen.label);
  }

  const fileSlug = safeFileSlug(event);
  const disposition = `attachment; filename="transcript-${fileSlug}.${format}"`;

  let body: Buffer | string;
  if (format === "txt") {
    body = buildTxt(title, dateLabel, lines);
  } else if (format === "rtf") {
    body = buildRtf(title, dateLabel, lines);
  } else {
    body = await buildDocx(title, dateLabel, lines);
  }

  const buf = typeof body === "string" ? Buffer.from(body, "utf8") : body;

  return new NextResponse(new Uint8Array(buf), {
    status: 200,
    headers: {
      "content-type": CONTENT_TYPES[format],
      "content-disposition": disposition,
      "content-length": String(buf.byteLength),
      "cache-control": "no-store",
    },
  });
}
